### PR TITLE
Add a docker-compose file for each compiler

### PR DESCRIPTION
**Pull request by IntelOrca**
This allows you to run the CI jobs on your computer using docker.

```sh
# Run them individually
docker-compose up openloco-gcc32
docker-compose up openloco-clang32
docker-compose up openloco-mingw32

# Run them all in parallel
docker-compose up
```

This should allow anyone to easily "build" openloco either on Windows (10 pro+), macOS or any Linux distro.

### CODE REVIEW

**Comment by janisozaur** [comment]
Nice!

Is there any way to extract the common parts of command line?

**Comment by IntelOrca** [comment]
This is my first attempt at docker-compose, very new to it so I don't know. I think you can move stuff into other files like an env file, but doesn't seem as clean.

**Comment by janisozaur** [comment]
Keep in mind those are all images targetting 32 bit builds, so maybe you would want to rename the first two images?

If we migrated all of the images to Fedora, that would also allow to save some space on the common base.

**Comment by IntelOrca** [comment]
@janisozaur I have renamed them.

**Pull request merged**
