### PR TITLE
ko-KR: Create the first translation

### PR DESCRIPTION
**Pull request by telk5093**
Half translated, I think. I will improve translations continuely.
I make a translation first of all whether OpenLoco still not support UTF-8 yet or not.

And i think it will be great to implement a **gender** for nouns as OpenTTD does.
Actually korean has no genders in noun, but I use it in OpenTTD to represent  **Josa**, which is a postposition attached right after a noun in Korean grammar, differ to whether a last sound (we call it batchim, 받침) exists or not.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Nice to see you've picked this up so quickly! Thank you!

You're right, OpenLoco does not support UTF-8 as of yet, or loading language files, for that matter. It's one of the things I'd like to have implemented soon as well, though!

As for different versions of the nouns, could you indicate where in particular you find them missing? We cannot add them right now, though, as the windows aren't implemented yet.

**Comment by Gymnasiast** [comment]
We saw you translate it on Twitch! :+1:

**Comment by telk5093** [comment]
@AaronVanGeffen Most of {STRINGID2} has ``(이)가`` or ``(을)를`` right after them, because it is unable to determine {STRINGID2} has their last sound as a consonant. (consonant: we attach 이/을, vowel: 가/를)

**Comment by AaronVanGeffen** [comment]
Right. Interestingly, OpenTTD seems to solve this with an actual [gender system](https://newgrf-specs.tt-wiki.net/wiki/NML:Language_files#Defining_genders). Very neat. Perhaps we could do something similar, but until all code has been implemented, I'm afraid that'll be low priority…

**Pull request merged**
