### PR TITLE
Fix #22: Try to find data files if wrong case for non-Windows platforms

### LINKED ISSUE #22: Case insensitive file loading needed for POSIX

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by janisozaur** [comment]
CI builds, but suggests formatting changes. Code LGTM, but haven't tested it. That might need hooking in some places for #14?

**Comment by IntelOrca** [comment]
How do I auto format?

**Comment by janisozaur** [comment]
`clang-format -i -style=file <path/to/file.cpp>`

**Comment by AaronVanGeffen** [comment]
Tested this on top of #12, which works. Renamed a few DAT files, including my `g1.DAT` to use different casing. Unfortunately, this does lead to them no longer being found, so this patch doesn't seem to have the intended effect.

**Pull request merged**
