### PR TITLE
Clean up code style of WindowManager

### PR DESCRIPTION
**Pull request by marijnvdwerf**
Because #193 is rather hard to oversee.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Thanks for splitting this off into its own PR. I really prefer this code style, too.

OpenRCT2 uses initial capitalisation for method names, too (`LikeThis` instead of `likeThis`). Is this something you'd like to adopt for OpenLoco, too?

**Comment by marijnvdwerf** [comment]
I'd rather not. UpperCamelCase is something I've so far only ever seen in C#; Java, Objective-C, Swift all use lowerCamelCase.

**Comment by AaronVanGeffen** [comment]
So, to summarise, the proposal is to do UpperCamelCase for class names and other types, and lowerCamelCase for method and variable names? I'm alright with that.

**Comment by marijnvdwerf** [comment]
Yeah. And always use getters/setters for fields, as opposed to `input::state(input_state state)` to set and `input::state()` to get.

**Comment by Gymnasiast** [comment]
I think we should have the same code style between OpenLoco and OpenRCT2. I'm okay with using lowerCamelCase for function names, which appears to be the only change to what we do in OpenRCT2 currently.

**Comment by IntelOrca** [comment]
Merge as cece7969a0f417ccec11065242ec9e1f871431b4

**Pull request closed without merging**
